from __future__ import annotations

INTENT_ORDER = [
    "TREASURY_OPERATION",
    "TREASURY_DATA_QUERY",
    "FINANCE_KNOWLEDGE_QA",
    "GENERAL_KNOWLEDGE_QA",
    "UNKNOWN",
]

INTENT_KEYWORDS = {
    "TREASURY_OPERATION": [
        "transfer order",
        "create transfer",
        "create payment",
        "download receipt",
        "receipt download",
        "创建付款",
        "发起付款",
        "创建支付",
        "发起支付",
        "创建转账",
        "发起转账",
        "执行转账",
        "下载回单",
        "下载单据",
    ],
    "TREASURY_DATA_QUERY": [
        "account balance",
        "balance",
        "account",
        "transaction",
        "transactions",
        "receipt status",
        "cash pool",
        "pool position",
        "query balance",
        "账户",
        "余额",
        "流水",
        "交易",
        "回单状态",
        "资金池",
    ],
    "FINANCE_KNOWLEDGE_QA": [
        "treasury policy",
        "treasury rule",
        "财资规则",
        "资金规则",
        "财资制度",
        "财资审批",
        "财资合规",
        "规则",
        "制度",
        "审批",
        "状态码",
        "要求",
        "合规",
        "银行",
        "转账",
        "回单",
        "资金用途",
        "资金审批",
        "bank",
        "rule",
        "policy",
        "approval",
    ],
    "GENERAL_KNOWLEDGE_QA": [
        "财务",
        "金融",
        "资金问题",
        "咨询",
        "分析",
        "处理",
        "finance",
    ],
}

UNKNOWN_INTENT_ANSWER = "系统暂不支持这类请求"
